name: first workflow

on:
  workflow_dispatch:
  
jobs:
  firstjob:
    runs-on: self-hosted
    steps:
    - name: firstJob script
      shell: bash
      run: echo Hello World! This is the first job
